### ISSUE TITLE
Suggestion: "invisible flag" system

### ISSUE THREAD

**Issue by McraftYT** [TownyAdvanced/FlagWar#111]
so in config by changing flag block by air feature will be activated:
so when in chunk plugin will count both town players in it and then it'll detect last man standing on chunk and if in time that's in config then land stays in their hands if not land becomes enemy's but not officially. that will be determined after war!

**Comment by TheFlagCourier** [comment]
I have no intention to implement this feature in FlagWar at this time. From what I remember, this sounds far too similar to how @LlmDl's EventWar TownBlock HP works.
