### ISSUE TITLE
OutlawTeleportEvent error

### ISSUE THREAD

**Issue by JustinDevB** [TownyAdvanced/FlagWar#78]
### What steps will reproduce the problem?
1. Be an outlaw and teleport to a town
2.
3.

### What is the expected output?
1. Allows it to happen during war
2.
3.

### What is your Towny version number?
Do not say "latest".
0.97.0.19

### What is your FlagWar version number?
Do not say "latest".
0.4.0

### What is your Spigot/Paper/Fork server version?
Do not say "latest". Run the `/version` command.

```shell
This server is running Purpur version git-Purpur-1396 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 92a00b8 on ver/1.17.1)
You are 1 version(s) behind
Previous version: git-Purpur-1391 (MC: 1.17.1)
```

### Please use a pastebin service to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly.
If you do skip this step then your ticket will most likely be deleted, and you will be asked to resubmit.**
None of these are relevant.

https://pastebin.com/ZsTUuidv

**Comment by LlmDl** [comment]
What sort of teleport is being used to teleport to the town?

**Comment by JustinDevB** [comment]
No idea, but should that matter? Shouldn’t OutlawTeleportEvent when towny attempts to teleport an outlaw out of a town?

**Comment by LlmDl** [comment]
I don't think I understand the instructions you've given for reproducing this. Please flesh it out.
