### ISSUE TITLE
Suggestion: PvP need to be force enabled on the attacking chunk

### ISSUE THREAD

**Issue by kenny1998cr** [TownyAdvanced/FlagWar#93]
**Please explain your feature request to the best of your abilities:**
Well, in my server people start a battle for the flag, everything works good BUT the most important, players cannot use PvP in the attacking chunk because the town/nation mayor set the PvP permission Off, so the attackers cannot stop the defenders.

So my suggestion is: force the PvP on the attacked chunk, 
If the defenders wins= Just go back to the perms that the mayor set up previously.
If the attackers wins= The normal warflag stuff, the winner keep the chunk.

Here I show a video with the example: https://youtu.be/aFfLULPQXeo

**Comment by LlmDl** [comment]
Last I tested, on the current version, pvp is enabled in the attacked area.

**Comment by kenny1998cr** [comment]
> 
> 
> Last I tested, on the current version, pvp is enabled in the attacked area.

Hello LlmDl thanks for you reply, im currently using towny 0.97.2.18 and Flagwar 0.5.1 and the same issue happening. Even worldguad is disabled.
Here's a video: https://youtu.be/4O5TtagW7h0

**Comment by kenny1998cr** [comment]
Nevermind, I just check and on the edge

**Comment by LlmDl** [comment]
```java
    @EventHandler
    public void onTownBlockPVPTestEvent(final TownBlockPVPTestEvent townBlockPVPTestEvent) {
        if (!FlagWarConfig.isAllowingAttacks()
        || !Cell.parse(townBlockPVPTestEvent.getTownBlock().getWorldCoord()).isUnderAttack()) {
            return;
        }
        townBlockPVPTestEvent.setPvp(true);
    }
```
Is the code which makes any plot with a flag in it have PVP on. I'll test this myself but I'm sure it was working.

**Comment by kenny1998cr** [comment]
> 
> 
> ```java
>     @EventHandler
>     public void onTownBlockPVPTestEvent(final TownBlockPVPTestEvent townBlockPVPTestEvent) {
>         if (!FlagWarConfig.isAllowingAttacks()
>         || !Cell.parse(townBlockPVPTestEvent.getTownBlock().getWorldCoord()).isUnderAttack()) {
>             return;
>         }
>         townBlockPVPTestEvent.setPvp(true);
>     }
> ```
> 
> Is the code which makes any plot with a flag in it have PVP on. I'll test this myself but I'm sure it was working.

I just made a clear install of Towny and FlagWar but the issue appear, also I have allow attacks on true

![imagen](https://user-images.githubusercontent.com/32584296/142081703-609b77a3-aa48-4de5-9796-bbe72bff4efe.png)

**Comment by LlmDl** [comment]
I've been able to reproduce it, I think I have a fix for it.

**Comment by kenny1998cr** [comment]
> 
> 
> I've been able to reproduce it, I think I have a fix for it.

Good ! And thanks for the fix LlmDl you are the best (I have to donate you for all the support :) ). This fix would take some time or is going to be quick? because my server need it asap, but take your time of course. Thanks again!.
